title: ELM Ensemble - Sally and Josh Messner, directors

baseurl: http://elmensemble.org
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://www.elmensemble.org'
  relativeLinks: 'http://www.elmensemble.org/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: 'CURRENT_DATETIME'
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "sticky"
        field:
          element: "checkbox"
          label: "Sticky at top"
          value: "false"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: 'CURRENT_DATETIME'
